### ISSUE TITLE
Can't Install IoT Edge extension in VS Code 

### ISSUE THREAD

**Issue by melzoghbi** [Microsoft/vscode-azure-iot-edge#103]
Hi,

I am using VS Code on Raspbian Stretch OS. This is installed from Package Cloud. When i try to install Azure IoT Edge extension i get the following error:

![image](https://user-images.githubusercontent.com/11993393/38390953-d3a8343c-38f0-11e8-8cd0-1e1bc8324a9f.png)

Any workaround to get this working? 

Thanks.

**Comment by formulahendry** [comment]
Hi @melzoghbi , please check your VS Code version and make sure the verson is >= 1.18.0

**Comment by melzoghbi** [comment]
Hi @formulahendry ,

I have v 1.14.0 and i do not have any updates! it seems i have to wait until package cloud release a new build since MS doesn't have Raspbian OS builds!

**Comment by formulahendry** [comment]
Hi @melzoghbi , have a quick search, maybe you could try below posts to install a newer VS Code version to use the IoT Edge extension: https://www.hanselman.com/blog/BuildingVisualStudioCodeOnARaspberryPi3.aspx http://dattabase.com/install-vs-code-raspberry-pi-3/

Closing this issue since it is related to VS Code itself, Feel free to reopen or create a new one if you have any issue.

**Comment by melzoghbi** [comment]
Thanks @formulahendry for the links! will give it a shot.
