### ISSUE TITLE
create nodejs module failed

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#131]
Repro on:
Mac/Ubuntu
Steps:
1.	Edge: New IoT Edge solution ->Select Nodejs Module -> Follow the steps and input required fields to create solution
Verify this error:
![image](https://user-images.githubusercontent.com/35018765/39394812-17694e70-4b09-11e8-9d02-d9c69bed8dca.png)

**Comment by LazarusX** [comment]
The root cause is that installing NPM packages globally on *nix systems requires admin privileges. However, the fix is not as simple as prepending a `sudo` to the command, because we use VS Code's output channel which disallows user input while `sudo` operations are interactive.

I came up with two workarounds:
1. Do not `npm i -g generator-azure-iot-edge-module` every time users add a Node.js module to the solution. Add the template to the document's prerequisite section or instruct users to install the template along with Yeoman with `npm i -g yo generator-azure-iot-edge-module`.
    * Cons: 1) One more prerequisite 2) Since `npm outdated -g` also requires `sudo`, we cannot ensure that users always have the latest version of the template.
2. Send the commands to terminal
    * Cons: All the cons of the "run in terminal" approach: will fail if there is a running operation in the terminal or existing text in the prompt; no way to tell if the operation succeeds, etc.

Personally I prefer 1 because we are unlikely to have too many major changes to the template in the future. Even if we are, we have other channels to inform users of the updates, e.g., document, readme, change log, pop ups, or output channel.

@adashen @formulahendry @shizn Any thoughts?
