### ISSUE TITLE
Start edge runtime failed

### ISSUE THREAD

**Issue by SLdragon** [Microsoft/vscode-azure-iot-edge#188]
System: Linux Ubuntu 16.04
Follow the steps to start the edge runtime:  

https://review.docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux?branch=release-iotedge-infra

Got error messages after starting the runtime: 

> systemctl status iotedge

iotedge.service - Azure IoT Edge daemon
   Loaded: loaded (/lib/systemd/system/iotedge.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-06-26 09:37:17 UTC; 1min 15s ago
     Docs: man:iotedged(8)
 Main PID: 46084 (iotedged)
    Tasks: 6
   Memory: 9.3M
      CPU: 14ms
   CGroup: /system.slice/iotedge.service
           └─46084 /usr/bin/iotedged -c /etc/iotedge/config.yaml

Jun 26 09:37:17 rentu-test-local iotedged[46084]: 2018-06-26T09:37:17Z [INFO] - Finished provisioning edge device.
Jun 26 09:37:17 rentu-test-local iotedged[46084]: 2018-06-26T09:37:17Z [INFO] - Starting management API...
Jun 26 09:37:17 rentu-test-local iotedged[46084]: 2018-06-26T09:37:17Z [INFO] - Listening on fd://iotedge.mgmt.socket/ with 1 thread for management API.
Jun 26 09:37:17 rentu-test-local iotedged[46084]: 2018-06-26T09:37:17Z [INFO] - Starting workload API...
Jun 26 09:37:17 rentu-test-local iotedged[46084]: 2018-06-26T09:37:17Z [INFO] - Listening on fd://iotedge.socket/ with 1 thread for workload API.
Jun 26 09:37:17 rentu-test-local iotedged[46084]: 2018-06-26T09:37:17Z [INFO] - Starting watchdog with 60 second frequency...
Jun 26 09:37:17 rentu-test-local iotedged[46084]: 2018-06-26T09:37:17Z [INFO] - Checking edge runtime status
Jun 26 09:37:18 rentu-test-local iotedged[46084]: 2018-06-26T09:37:18Z [INFO] - Edge runtime status is failed, starting module now...
Jun 26 09:38:17 rentu-test-local iotedged[46084]: 2018-06-26T09:38:17Z [INFO] - Checking edge runtime status
Jun 26 09:38:18 rentu-test-local iotedged[46084]: 2018-06-26T09:38:18Z [INFO] - Edge runtime status is failed, starting module now...

**Comment by maksokami** [comment]
Same on Deb9:

. . .
Sep 17 20:31:41 Test systemd[1]: Stopped Azure IoT Edge daemon.
Sep 17 20:31:41 Test systemd[1]: Started Azure IoT Edge daemon.
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Starting Azure IoT Edge Security Daemon
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Version - 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Using config file: /etc/iotedge/config.yaml
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Using runtime network id azure-iot-edge
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Initializing the module runtime...
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Finished initializing the module runtime.
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Configuring /storage/var/lib/iotedge as the home directory.
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Configuring certificates...
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Configuring the Device CA certificate using "/home/mo…ert.pem".
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Configuring the Device private key using "/home/Test/…key.pem".
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Configuring the trusted CA certificates using "/home/…ert.pem".
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Finished configuring certificates.
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Initializing hsm...
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Finished initializing hsm.
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Detecting if configuration file has changed...
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - No change to configuration file detected.
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Provisioning edge device...
Sep 17 20:31:41 Test iotedged[3674]: 2018-09-17T20:31:41Z [INFO] - Starting DPS registration with scope_id "0ne00000063"…mpt4uiqa"
Sep 17 20:31:56 Test iotedged[3674]: 2018-09-17T20:31:56Z [INFO] - DPS registration assigned device "mks-hermes-test" in…ices.net"
Sep 17 20:31:56 Test iotedged[3674]: 2018-09-17T20:31:56Z [INFO] - Successful DPS provisioning. This will trigger reconf… modules.
Sep 17 20:31:56 Test iotedged[3674]: 2018-09-17T20:31:56Z [INFO] - Finished provisioning edge device.
Sep 17 20:31:56 Test iotedged[3674]: 2018-09-17T20:31:56Z [INFO] - Starting management API...
Sep 17 20:31:56 Test iotedged[3674]: 2018-09-17T20:31:56Z [INFO] - Listening on fd://0/ with 1 thread for management API.
Sep 17 20:31:56 Test iotedged[3674]: 2018-09-17T20:31:56Z [INFO] - Starting workload API...
Sep 17 20:31:56 Test iotedged[3674]: 2018-09-17T20:31:56Z [INFO] - Listening on fd://1/ with 1 thread for workload API.
Sep 17 20:31:56 Test iotedged[3674]: 2018-09-17T20:31:56Z [INFO] - Starting watchdog with 60 second frequency...
Sep 17 20:31:56 Test iotedged[3674]: 2018-09-17T20:31:56Z [INFO] - Checking edge runtime status
Sep 17 20:31:56 Test iotedged[3674]: 2018-09-17T20:31:56Z [INFO] - Creating and starting edge runtime module edgeAgent
Sep 17 20:31:56 Test iotedged[3674]: 2018-09-17T20:31:56Z [INFO] - Updating identity for module $edgeAgent
Sep 17 20:32:28 Test iotedged[3674]: 2018-09-17T20:32:28Z [INFO] - [work] - - - [2018-09-17 20:32:28.991566920 UTC] "GET…pid(3727)
Sep 17 20:32:29 Test iotedged[3674]: 2018-09-17T20:32:29Z [INFO] - [mgmt] - - - [2018-09-17 20:32:29.878352440 UTC] "POS…pid(3727)
Sep 17 20:32:56 Test iotedged[3674]: 2018-09-17T20:32:56Z [INFO] - Checking edge runtime status
Sep 17 20:32:56 Test iotedged[3674]: 2018-09-17T20:32:56Z [INFO] - Edge runtime status is failed, starting module now...
Sep 17 20:33:26 Test iotedged[3674]: 2018-09-17T20:33:26Z [INFO] - [work] - - - [2018-09-17 20:33:26.605611800 UTC] "GET…pid(3947)
Sep 17 20:33:27 Test iotedged[3674]: 2018-09-17T20:33:27Z [INFO] - [mgmt] - - - [2018-09-17 20:33:27.240275160 UTC] "POS…pid(3947)
Sep 17 20:33:56 Test iotedged[3674]: 2018-09-17T20:33:56Z [INFO] - Checking edge runtime status
Sep 17 20:33:56 Test iotedged[3674]: 2018-09-17T20:33:56Z [INFO] - Edge runtime status is failed, starting module now...


----------------sudo systemctl status iotedge------------------
● iotedge.service - Azure IoT Edge daemon
   Loaded: loaded (/lib/systemd/system/iotedge.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-09-17 20:31:41 UTC; 3min 13s ago
     Docs: man:iotedged(8)
 Main PID: 3674 (iotedged)
   Memory: 2.0M
      CPU: 409ms
   CGroup: /system.slice/iotedge.service
           └─3674 /usr/bin/iotedged -c /etc/iotedge/config.yaml


---------------------docker logs edgeAgent------------------------------
2018-09-17 20:34:09.097 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via AMQP...
2018-09-17 20:34:24.551 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
2018-09-17 20:34:28.275 +00:00 [FTL] - Fatal error starting Agent.
Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling Getting System Info: 0

, StatusCode:404, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation) in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 204
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.GetSystemInfoAsync() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 118
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.RuntimeInfoProvider`1.GetSystemInfo() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/RuntimeInfoProvider.cs:line 33
   at Microsoft.Azure.Devices.Edge.Agent.Docker.DockerEnvironmentProvider.CreateAsync(IRuntimeInfoProvider runtimeInfoProvider, IEntityStore`2 store, IRestartPolicyManager restartPolicyManager) in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerEnvironmentProvider.cs:line 30
   at Microsoft.Azure.Devices.Edge.Agent.Service.Modules.EdgeletModule.<>c.<<Load>b__9_6>d.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/EdgeletModule.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.Service.Modules.AgentModule.<>c.<<Load>b__13_14>d.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/AgentModule.cs:line 242
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 174
2018-09-17 20:34:29.357 +00:00 [INF] - Termination requested, closing.
[2018-09-17 20:34:58 +00:00]: Starting Edge Agent
[09/17/2018 08:34:59.342 PM] Edge Agent Main()
2018-09-17 20:35:02.989 +00:00 [INF] - Starting module management agent.
2018-09-17 20:35:06.022 +00:00 [INF] - Version - 1.0.0-rc1.14370730 (409cdf6d890828b1bca22fbe6d560fad395c3611)

--------------- sudo iotedge list --------------
An error in the management http client occurred.
        caused by: Client error
