### ISSUE TITLE
Support new "modulesContent"

### ISSUE THREAD

**Issue by adashen** [Microsoft/vscode-azure-iot-edge#203]

**Comment by adashen** [comment]
Test:
1. New solution -> now the first element under root is "modulesContent" instead of "moduleContent"
2. Open an old solution (moduleContent) make sure
(1) Add module/build module/generate manifiest  works correctly. And the generated manifiest has "modulesContent" instead of "moduleContent"
(2) Deploy the solution with generated manifest, it works correctly.

**Comment by czgtest** [comment]
2.Open an old solution (moduleContent) make sure
(1) Add module/build module/generate manifiest works correctly. And the generated manifiest has "modulesContent" instead of "moduleContent"

 test pass for it

(2) Deploy the solution with generated manifest, it works correctly.

right-click edge device and select "create deployment for single device"

Deployment failed. Error: Request failed with status code 400
![image](https://user-images.githubusercontent.com/35018765/43633290-5d03dc9c-973b-11e8-8a12-6e67a982c712.png)
