### ISSUE TITLE
deployment.template.json and launch.json are still updated if there is error in create module

### ISSUE THREAD

**Issue by adashen** [Microsoft/vscode-azure-iot-edge#65]
1. install the released function template (to test the legacy template)
2. Select deployment.template.json to add module
3. Use C# function module type
4. Error shows since there is no "-r" option in legacy template
5. Check the deployment.template.json and launch.json, however, they are both updated.

Desired:
if new module failed, deployment.template.json and launch.json should not be updated

**Comment by czgtest** [comment]
this issue fix work, 

1.install the released function template (to test the legacy template)
Select deployment.template.json to add module
2.Use C# function module type
3.Error shows since the module name is invalid.
![image](https://user-images.githubusercontent.com/35018765/37693067-33332466-2cf8-11e8-946c-172c1656d875.png)

Check the deployment.template.json and launch.json, now they are not updated.
