### ISSUE TITLE
[IoT Edge Solution] Deployment template/Build Solution support for platforms

### ISSUE THREAD

**Issue by jessebenson** [Microsoft/vscode-azure-iot-edge#92]
The name 'deployment.template.json' is hard-coded for the 'Generate IoT Edge Deployment Manifest' command.  There are significant differences when building arm32v7 (e.g. the container images for systemModules are different, plus all my module images).  It would be nice to support platforms:

[1] 'Generate IoT Edge Deployment Manifest' and 'Build IoT Edge Solution' should have a parameter to pick which platform to build from the same set in module.json (amd64/amd64.debug/arm32v7/windows-amd64), which is filled in as a parameter in the deployment.template.json - ${MODULES.<name>.PLATFORM}

**Comment by adashen** [comment]
@jessebenson Currently, if you would like to change the platform, you can specify the platform in the image of the modules in the deployment.template.json. for example ${MODULES.SAMPLE.amd64} , if you have provided the platform "arm32v7", and you want to change to "arm32v7", you can use ${MODULES.SAMPLE.arm32v7}. 

So does your suggestion mean to provide another parameter ${MODULES.SAMPLE.PLATFORM}, to let user choose the platform? The problem here is each module under modules folder may have their own naming of the platform. It does not assume the platform definition are shared across the modules. 

I think your suggestion is valid. And one workaround is you can use "environment variable" to specify the image, and currently, the extension has already been able to expand the environment variables in the deployment.templatejson

**Comment by jessebenson** [comment]
Providing amd64/arm32v7 for developer modules is relatively easy to change (specify ${MODULES.<name>.amd64} or ${MODULES.<name>.arm32v7}).  But the more painful part is the systemModules.  So everytime I switch between local development on x64 and device deployment on arm32v7, I have to change the systemModules:

For x64:
```
microsoft/azureiotedge-agent:1.0-preview
microsoft/azureiotedge-hub:1.0-preview
```

For arm32v7:
```
microsoft/azureiotedge-agent:1.0.0-preview021-linux-arm32v7
microsoft/azureiotedge-hub:1.0.0-preview021-linux-arm32v7
```

My workaround was, I filled in the deployment.template.json for each platform, built it, and then checked in the generated deployment.json files for amd64/amd64.debug/arm32v7.

**Comment by adashen** [comment]
@jessebenson microsoft/azureiotedge-agent:1.0-preview and microsoft/azureiotedge-hub:1.0-preview are supposed to be cross-platform image. That means if running arm32v7, it will use the arm32v7 version image. If there is issue on this. We need to report the issue to IoT Edge team.

**Comment by jessebenson** [comment]
@adashen - this may be specific to deploying on arm64 devices.  Agree this sounds like it should be reported to IoT Edge team instead.  When I specify `microsoft/azureiotedge-agent:1.0-preview` and `microsoft/azureiotedge-hub:1.0-preview` in the deployment.json, it fails to deploy to the device.

```
%> sudo docker logs edgeAgent
---> (Inner Exception #0) Docker.DotNet.DockerContainerNotFoundException: Docker API responded with status code=NotFound, response={"message":"No such image: microsoft/azureiotedge-hub:1.0-preview"}
```

Indeed, if I try to manually pull that image on the device, it fails:
```
%> sudo docker pull microsoft/azureiotedge-agent:1.0-preview
1.0-preview: Pulling from microsoft/azureiotedge-agent
no matching manifest for linux/arm64 in the manifest list entries
%>
%> sudo docker pull microsoft/azureiotedge-hub:1.0-preview
1.0-preview: Pulling from microsoft/azureiotedge-hub
no matching manifest for linux/arm64 in the manifest list entries
```

**Comment by adashen** [comment]
need ask edge to support arm64. close here
